### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by officialmahak** [mehulmk/Shopify-flutter-demo#2]
Hello,

How can I get a token from my Shopify Store?

Regards

**Comment by mehulmk** [comment]
Hello,
https://shopify.dev/apps/auth/basic-http
follow this link and generate **Shopify access token** for private app.
its looks like  **shppa_adgjgsdfsjkgdjfsgdjgh**
and base url is like   **https://{shop}.myshopify.com/admin/api/2022-01/**
Let me know if need any more help
Thanks

**Comment by officialmahak** [comment]
Hello,

I change API and my Shopify URL in key_util.dart
After running this app it shows errors
https://ibb.co/R6WKcZv

Regards

**Comment by officialmahak** [comment]
I already tried API, Shared Secret & Storefront access token but same issue

**Comment by CodeGetIT** [comment]
we are getting the error message

**Comment by CodeGetIT** [comment]
can you please help me out

**Comment by mehulmk** [comment]
Sorry for late reply

1)You need to add product to you shopify data base(i have already add dummy product github link in readme file).
![Screenshot 2022-01-18 at 3 41 12 PM](https://user-images.githubusercontent.com/58975707/149917071-308994e0-50a9-4e6d-b064-c25a5b7857bc.png)

2)and then you need to create different collection for category, offer, banner etc
![Screenshot 2022-01-18 at 3 45 01 PM](https://user-images.githubusercontent.com/58975707/149917845-db2e5a3e-5b7a-4c24-8d34-cdd172fe9898.png)

3)then replace that collection id in [key_util.dart file](https://github.com/mehulmk/Shopify-flutter-demo/blob/main/lib/utility/key_util.dart)
![Screenshot 2022-01-18 at 3 57 58 PM](https://user-images.githubusercontent.com/58975707/149920263-11d322dd-e9f0-45d6-a1a6-71177a8e7354.png)

![Screenshot 2022-01-18 at 4 01 42 PM](https://user-images.githubusercontent.com/58975707/149922940-c8382758-ad09-4cd1-9d82-59ceff38fc4f.png)

let me know if you need more help
Thanks

**Comment by officialmahak** [comment]
Hello,

Please check 
I changed all the Collection ID but the same issue

<img width="1138" alt="Screenshot 2022-01-18 at 10 05 37 PM" src="https://user-images.githubusercontent.com/86548005/149979175-13e3fbbb-99d2-4013-8c92-a12a4608dd00.png">


Regards

**Comment by mehulmk** [comment]
Hello,
can you try to call this( _https://{shop}.com/admin/api/2021-10/collects.json_ ) api in post man.
You need to pass **X-Shopify-Access-Token** in header.
and it must return list of all collection of your shopify database.
Like this...
![Screenshot 2022-01-29 at 10 59 36 AM](https://user-images.githubusercontent.com/58975707/151648874-8da32c31-d97e-40ba-a8ec-6fd1cf2c438d.png)

And if its not return collection list then you need to do some research about way this api is not working and try to make this api working.
Once this api return the collection list then i think in your app data will reflected.
Let me know you need any more help
thanks

**Comment by officialmahak** [comment]
Hello,

Thanks for help

It returns 401 error with 
{
    "errors": "[API] Invalid API key or access token (unrecognized login or wrong password)"
}

Regards

**Comment by mehulmk** [comment]
It's seems like you are using wrong access token.
Token looks like _shppa_adgjgsdfsjkgdjfsgdjgh_ this(private app token start with **shppa...**.
So pls try to replace the token maybe after that it will be working fine.
Let me know if you need more help.
Thanks

**Comment by officialmahak** [comment]
Hello,

If I enter my Example URL then its works fine and if I enter my store URL with https://{shop}.com/admin/api/2021-10/collects.json then it shows 401

Best Regards

**Comment by mehulmk** [comment]
My example url means you store url right ?

**Comment by officialmahak** [comment]
yes
https://sakurameds.myshopify.com/admin/api/2022-01/collects.json

If you want then i will privately message you my key and secret

Regards

**Comment by mehulmk** [comment]
Right you need to use your shope url.
https://{shop}.com/admin/api/2021-10/collects.json here I hide my store domain with **{shop}**.
So use your url in key_util.dart.(in base_url params)

**Comment by officialmahak** [comment]
Thanks

Could you please test my store keys on postman?
please drop your email or anything
i will provide you my credentials 

Regards

**Comment by mehulmk** [comment]
Sure,
I had added developer contact details in [ReadMe](https://github.com/mehulmk/Shopify-flutter-demo#readme) file.

**Comment by officialmahak** [comment]
Please check your Linkedin

Regards
