### ISSUE TITLE
it is not fetching products, it fetches when disable web security 

### ISSUE THREAD

**Issue by saqoo06** [mehulmk/Shopify-flutter-demo#3]
it is not fetching products or categories, it only show data when web security is disabled..
How to fix that issue

**Comment by mehulmk** [comment]
Hi Saqlain,
In Which platfrom are you facing this problem flutter web or mobile?

**Comment by saqoo06** [comment]
> Hi Saqlain, In Which platfrom are you facing this problem flutter web or mobile?

I am facing this problem in web and mobile both
in mobile responce is not showing

**Comment by mehulmk** [comment]
Okey
Can you share the api error ?

**Comment by saqoo06** [comment]
> Okey Can you share the api error ?

before disabling web security i got an error xhttp error

**Comment by mehulmk** [comment]
i need actual error response so i can do R&D on it.

**Comment by saqoo06** [comment]
> Okey Can you share the api error ?

when i debug in mobile it shows gradle build failed message

**Comment by mehulmk** [comment]
can you past screenshot of that error ?

**Comment by saqoo06** [comment]
> can you past screenshot or that error ?

ok I am sharing with you that error
how to enable web security back then i can show you

**Comment by saqoo06** [comment]
![image](https://user-images.githubusercontent.com/114026507/191461809-53686a46-6721-47fb-acdf-137f30ec88c8.png)

**Comment by saqoo06** [comment]
let me explain I have same issues which was closed previous

**Comment by saqoo06** [comment]
when i install i got printed "error" in ui

**Comment by mehulmk** [comment]
Okey
so can you share that error which are printed in console ?

**Comment by saqoo06** [comment]
warning: 'C:/flutter' is owned by:
	'S-1-5-32-544'
but the current user is:
	'S-1-5-21-1930637631-2438606357-2480582011-1001'
Launching lib\main.dart on google Pixel 2 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find io.flutter:x86_release:1.0.0-a4ff2c53d84ca78702bc3be6c7ef0788ffca01d3.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/flutter/x86_release/1.0.0-a4ff2c53d84ca78702bc3be6c7ef0788ffca01d3/x86_release-1.0.0-a4ff2c53d84ca78702bc3be6c7ef0788ffca01d3.pom
       - https://repo.maven.apache.org/maven2/io/flutter/x86_release/1.0.0-a4ff2c53d84ca78702bc3be6c7ef0788ffca01d3/x86_release-1.0.0-a4ff2c53d84ca78702bc3be6c7ef0788ffca01d3.pom
       - https://storage.googleapis.com/download.flutter.io/io/flutter/x86_release/1.0.0-a4ff2c53d84ca78702bc3be6c7ef0788ffca01d3/x86_release-1.0.0-a4ff2c53d84ca78702bc3be6c7ef0788ffca01d3.pom
     Required by:
         project :app
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 56s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by saqoo06** [comment]
I will send you an other error

**Comment by mehulmk** [comment]
hello
i have updated the android target version and kotlin version 
so take pull and try to run the app in android, mostly now you will not see that gradle related error.

**Comment by saqoo06** [comment]
> hello i have updated the android target version and kotlin version so take pull and try to run the app in android, mostly now you will not see that gradle related error.

where you updated those files in this github project

**Comment by mehulmk** [comment]
see the last commit 
https://github.com/mehulmk/Shopify-flutter-demo/commit/c1db2b7338d7e381a495553c9d367a481f7528af

**Comment by saqoo06** [comment]
Do I have to download it again?

**Comment by saqoo06** [comment]
Do I Have to Download again this Project?

**Comment by mehulmk** [comment]
git pull origin main 
Run this command if you have clone the project
 
or if you have downloaded the zip file the download it again or change the file base on lat commit.

**Comment by saqoo06** [comment]
Thanks but web security issue

**Comment by mehulmk** [comment]
I am checking it give me some time i will update you.

**Comment by saqoo06** [comment]
Did you Update Kotlin Plugin

**Comment by mehulmk** [comment]
Hello 
That web security issue is related to the CROS.

To fix that issue need to add CROS proxy to the shopify admin, but i don't have much experience on shopify.
so i will update you later once i will get the proper step to setup cros in admin or any other way.

until that you can try it from your side maybe you will get any solution or else disable the web security from chrome and use it.

Links:
https://shopify.dev/apps/online-store/app-proxies
https://github.com/flutterchina/dio/issues/750

**Comment by mehulmk** [comment]
> Did you Update Kotlin Plugin

Yes

**Comment by saqoo06** [comment]
Thanks a lot i will check and then i tell you

**Comment by saqoo06** [comment]
I got an error upgrade to gradle 7.3.1 
![image](https://user-images.githubusercontent.com/114026507/191589790-967b48b4-f45b-43bb-91e0-2aa0fcf4f2f1.png)

**Comment by saqoo06** [comment]
![image](https://user-images.githubusercontent.com/114026507/191601595-95191fc2-306e-453a-9a10-10a417f1c200.png)

**Comment by saqoo06** [comment]
![image](https://user-images.githubusercontent.com/114026507/191613123-d10a2d1f-c86c-4efc-a743-8307976bcd37.png)
during installation

**Comment by saqoo06** [comment]
After Installation in Mobile
![image](https://user-images.githubusercontent.com/114026507/191613266-f46b6ce6-9087-4b45-856e-b96e11584412.png)

**Comment by saqoo06** [comment]
![image](https://user-images.githubusercontent.com/114026507/191614364-adec4daa-fcad-4464-8813-7563715c13bc.png)

**Comment by saqoo06** [comment]
I got Response thanks a lot
But its taking too much time to build an apk 
i don't know why it is taking time
waiting for your response

**Comment by saqoo06** [comment]
![image](https://user-images.githubusercontent.com/114026507/191996927-c9541c29-9063-4915-8814-d6c48fb2133a.png)

**Comment by saqoo06** [comment]
![image](https://user-images.githubusercontent.com/114026507/191996998-6ba5bc03-8466-4d82-9e6d-2dafdd127ae0.png)

**Comment by mehulmk** [comment]
hello,
sorry for late reply i was busy at work.
need any help from my side ??

**Comment by mehulmk** [comment]
for now i will close this issue.
you can create new issue if you needed more help.
