### ISSUE TITLE
riverpods ，how to use with？

### ISSUE THREAD

**Issue by shaoting0730** [mehulmk/Shopify-flutter-demo#4]
riverpods ，how to use with？
The documentation shows that using  ConsumerStatefulWidget，but web you bug. https://github.com/rrousselGit/riverpod/issues/1854

**Comment by mehulmk** [comment]
can you add more details for this issue ?

**Comment by shaoting0730** [comment]
thanks，it is ok , i use getx.......  
i use riverpod, have some confused.....
https://github.com/pheromone/Flutter_learn_demo/tree/master/%E5%85%B6%E4%BB%96/%E6%A1%88%E4%BE%8B/riverpod_pro
